#!/usr/bin/env python3
"""Convert licensed Cardigann catalogs into deterministic IndexLoom definitions."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "definitions"
DEFAULT_MANIFEST = ROOT / "catalog.json"
GENERATED_BY = "indexloom-importer/v1"
SCHEMA_VERSION = "indexloom.io/v1alpha1"
SOURCE_LICENSE = "GPL-2.0-only"

JACKETT_PROJECT = "jackett"
JACKETT_REPOSITORY = "https://github.com/Jackett/Jackett"
PROWLARR_PROJECT = "prowlarr-indexers"
PROWLARR_REPOSITORY = "https://github.com/Prowlarr/Indexers"

SOURCE_KEYS = {
    "caps",
    "certificates",
    "description",
    "download",
    "encoding",
    "followredirect",
    "id",
    "language",
    "legacylinks",
    "links",
    "login",
    "name",
    "replaces",
    "requestDelay",
    "search",
    "settings",
    "testlinktorrent",
    "type",
}

HEX_40 = re.compile(r"^[0-9a-f]{40}$")
CANONICAL_ID = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
GENERATED_MARKER = "# Generated by indexloom-importer/v1; do not edit by hand."


class Yaml12Loader(getattr(yaml, "CSafeLoader", yaml.SafeLoader)):
    """Safe loader implementing the YAML 1.2 core scalar rules we rely on."""


Yaml12Loader.yaml_implicit_resolvers = {
    key: list(value) for key, value in Yaml12Loader.yaml_implicit_resolvers.items()
}
for first_character, resolvers in list(Yaml12Loader.yaml_implicit_resolvers.items()):
    Yaml12Loader.yaml_implicit_resolvers[first_character] = [
        (tag, pattern)
        for tag, pattern in resolvers
        if tag
        not in {
            "tag:yaml.org,2002:bool",
            "tag:yaml.org,2002:int",
            "tag:yaml.org,2002:timestamp",
        }
    ]
Yaml12Loader.add_implicit_resolver(
    "tag:yaml.org,2002:bool",
    re.compile(r"^(?:true|false)$", re.IGNORECASE),
    list("tTfF"),
)
Yaml12Loader.add_implicit_resolver(
    "tag:yaml.org,2002:int",
    re.compile(
        r"^(?:[-+]?0b[0-1]+|[-+]?0o[0-7]+|[-+]?(?:0|[1-9][0-9]*)|[-+]?0x[0-9a-fA-F]+)$"
    ),
    list("-+0123456789"),
)


class StableDumper(getattr(yaml, "CSafeDumper", yaml.SafeDumper)):
    """Dumper that avoids aliases and indents sequences under their keys."""

    def ignore_aliases(self, data: Any) -> bool:
        return True

    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        return super().increase_indent(flow, False)


@dataclass(frozen=True)
class Candidate:
    """One upstream definition and its immutable provenance."""

    project: str
    repository: str
    revision: str
    repository_root: Path
    path: Path
    document: dict[str, Any]
    source_bytes: bytes

    @property
    def source_id(self) -> str:
        return str(self.document["id"])

    @property
    def canonical_id(self) -> str:
        return canonicalize_id(self.source_id)

    @property
    def relative_path(self) -> str:
        return self.path.relative_to(self.repository_root).as_posix()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jackett-root", type=Path, required=True)
    parser.add_argument("--jackett-revision", required=True)
    parser.add_argument("--prowlarr-root", type=Path, required=True)
    parser.add_argument("--prowlarr-revision", required=True)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    return parser.parse_args()


def canonicalize_id(source_id: str) -> str:
    identifier = re.sub(r"[^a-z0-9]+", "-", source_id.lower()).strip("-")
    if not CANONICAL_ID.fullmatch(identifier):
        raise ValueError(f"cannot canonicalize indexer ID {source_id!r}")
    return identifier


def load_document(path: Path) -> tuple[dict[str, Any], bytes]:
    source_bytes = path.read_bytes()
    documents = list(yaml.load_all(source_bytes.decode("utf-8-sig"), Loader=Yaml12Loader))
    if len(documents) != 1 or not isinstance(documents[0], dict):
        raise ValueError(f"{path}: expected exactly one YAML mapping")
    document = documents[0]
    unknown = set(document) - SOURCE_KEYS
    if unknown:
        raise ValueError(f"{path}: unsupported top-level keys: {sorted(unknown)}")
    missing = {
        "caps",
        "description",
        "encoding",
        "id",
        "language",
        "links",
        "name",
        "search",
        "type",
    } - set(document)
    if missing:
        raise ValueError(f"{path}: missing required keys: {sorted(missing)}")
    if not isinstance(document["links"], list) or not document["links"]:
        raise ValueError(f"{path}: links must be a non-empty list")
    return document, source_bytes


def discover(
    *,
    project: str,
    repository: str,
    revision: str,
    repository_root: Path,
    definition_root: Path,
    recursive: bool,
) -> list[Candidate]:
    if not HEX_40.fullmatch(revision):
        raise ValueError(f"{project}: revision must be a full lowercase Git SHA")
    pattern = "**/*.yml" if recursive else "*.yml"
    candidates: list[Candidate] = []
    for path in sorted(definition_root.glob(pattern)):
        if not path.is_file() or path.is_symlink():
            continue
        document, source_bytes = load_document(path)
        candidates.append(
            Candidate(
                project=project,
                repository=repository,
                revision=revision,
                repository_root=repository_root,
                path=path,
                document=document,
                source_bytes=source_bytes,
            )
        )
    return candidates


def normalized_name(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.casefold())


def normalized_hosts(document: dict[str, Any]) -> tuple[str, ...]:
    hosts: set[str] = set()
    for link in document.get("links", []):
        host = (urlsplit(str(link)).hostname or "").casefold()
        if host.startswith("www."):
            host = host[4:]
        if host:
            hosts.add(host)
    return tuple(sorted(hosts))


def site_identity(candidate: Candidate) -> tuple[str, tuple[str, ...]]:
    return normalized_name(str(candidate.document["name"])), normalized_hosts(candidate.document)


def canonical_value(value: Any) -> Any:
    """Encode YAML values losslessly for deterministic semantic hashing."""
    if value is None:
        return ["null"]
    if isinstance(value, bool):
        return ["bool", value]
    if isinstance(value, int):
        return ["int", str(value)]
    if isinstance(value, float):
        return ["float", value.hex()]
    if isinstance(value, str):
        return ["str", value]
    if isinstance(value, list):
        return ["sequence", [canonical_value(item) for item in value]]
    if isinstance(value, dict):
        items = [
            [canonical_value(key), canonical_value(item)]
            for key, item in value.items()
        ]
        items.sort(
            key=lambda pair: json.dumps(
                pair[0], ensure_ascii=False, separators=(",", ":")
            )
        )
        return ["mapping", items]
    raise TypeError(f"unsupported YAML value type: {type(value).__name__}")


def canonical_json(value: Any) -> bytes:
    return json.dumps(
        canonical_value(value),
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")


def sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def convert(candidate: Candidate) -> dict[str, Any]:
    source = candidate.document
    implementation: dict[str, Any] = {}
    implementation["engine"] = "cardigann"
    implementation["encoding"] = source["encoding"]
    if "followredirect" in source:
        implementation["followRedirects"] = source["followredirect"]
    if "testlinktorrent" in source:
        implementation["testLinkTorrent"] = source["testlinktorrent"]
    if "requestDelay" in source:
        implementation["requestDelaySeconds"] = source["requestDelay"]
    if "certificates" in source:
        implementation["certificates"] = source["certificates"]
    implementation["capabilities"] = source["caps"]
    implementation["settings"] = source.get("settings", [])
    if "login" in source:
        implementation["authentication"] = source["login"]
    if "download" in source:
        implementation["download"] = source["download"]
    implementation["search"] = source["search"]

    source_record: dict[str, Any] = {}
    source_record["project"] = candidate.project
    source_record["repository"] = candidate.repository
    source_record["revision"] = candidate.revision
    source_record["path"] = candidate.relative_path
    source_record["sourceId"] = candidate.source_id
    source_record["license"] = SOURCE_LICENSE
    source_record["fileSha256"] = sha256(candidate.source_bytes)
    source_record["contentSha256"] = sha256(canonical_json(source))

    metadata: dict[str, Any] = {}
    metadata["id"] = candidate.canonical_id
    metadata["name"] = source["name"]
    metadata["description"] = source["description"]
    metadata["language"] = source["language"]

    spec: dict[str, Any] = {}
    spec["protocol"] = "torrent"
    spec["privacy"] = source["type"]
    spec["baseUrls"] = source["links"]
    if "legacylinks" in source:
        spec["legacyUrls"] = source["legacylinks"]
    if "replaces" in source:
        spec["replacedIds"] = [canonicalize_id(str(item)) for item in source["replaces"]]
    spec["implementation"] = implementation

    definition: dict[str, Any] = {}
    definition["apiVersion"] = SCHEMA_VERSION
    definition["kind"] = "Indexer"
    definition["metadata"] = metadata
    definition["provenance"] = {
        "generatedBy": GENERATED_BY,
        "source": source_record,
    }
    definition["spec"] = spec
    return definition


def render(definition: dict[str, Any]) -> bytes:
    body = yaml.dump(
        definition,
        Dumper=StableDumper,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=120,
    )
    header = (
        "# SPDX-FileCopyrightText: Jackett and Prowlarr Indexers contributors\n"
        "# SPDX-License-Identifier: GPL-2.0-only\n"
        f"{GENERATED_MARKER}\n"
    )
    return (header + body).encode("utf-8")


def select_candidates(
    jackett: list[Candidate], prowlarr: list[Candidate]
) -> tuple[list[Candidate], dict[str, Any]]:
    selected_by_id: dict[str, Candidate] = {}
    identity_to_id: dict[tuple[str, tuple[str, ...]], str] = {}
    for candidate in jackett:
        identifier = candidate.canonical_id
        if identifier in selected_by_id:
            raise ValueError(f"duplicate canonical Jackett ID: {identifier}")
        selected_by_id[identifier] = candidate
        identity_to_id.setdefault(site_identity(candidate), identifier)

    same_id = 0
    same_id_equal = 0
    aliases: list[dict[str, str]] = []
    selected_from_prowlarr = 0
    for candidate in prowlarr:
        identifier = candidate.canonical_id
        existing = selected_by_id.get(identifier)
        if existing is not None:
            same_id += 1
            if canonical_json(existing.document) == canonical_json(candidate.document):
                same_id_equal += 1
            continue

        identity = site_identity(candidate)
        if identity in identity_to_id:
            aliases.append(
                {
                    "sourceId": candidate.source_id,
                    "canonicalId": identity_to_id[identity],
                    "reason": "same normalized name and base URL set",
                }
            )
            continue

        selected_by_id[identifier] = candidate
        identity_to_id[identity] = identifier
        selected_from_prowlarr += 1

    report = {
        "strategy": "prefer Jackett for matching IDs; collapse cross-ID site aliases",
        "sameId": same_id,
        "sameIdSemanticallyEqual": same_id_equal,
        "sameIdDifferent": same_id - same_id_equal,
        "aliases": sorted(aliases, key=lambda item: item["sourceId"]),
        "selectedFromProwlarr": selected_from_prowlarr,
    }
    return sorted(selected_by_id.values(), key=lambda item: item.canonical_id), report


def prepare_output(output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    for path in output.glob("*.yml"):
        first_lines = path.read_text(encoding="utf-8", errors="replace").splitlines()[:4]
        if GENERATED_MARKER not in first_lines:
            raise ValueError(f"refusing to replace non-generated definition: {path}")
        path.unlink()
    gitkeep = output / ".gitkeep"
    if gitkeep.exists():
        gitkeep.unlink()


def write_catalog(
    candidates: list[Candidate],
    output: Path,
    manifest_path: Path,
    jackett_count: int,
    prowlarr_count: int,
    deduplication: dict[str, Any],
    jackett_revision: str,
    prowlarr_revision: str,
) -> None:
    prepare_output(output)
    entries: list[dict[str, Any]] = []
    for candidate in candidates:
        definition = convert(candidate)
        rendered = render(definition)
        target = output / f"{candidate.canonical_id}.yml"
        target.write_bytes(rendered)
        entries.append(
            {
                "id": candidate.canonical_id,
                "path": target.relative_to(ROOT).as_posix(),
                "sha256": sha256(rendered),
                "sourceProject": candidate.project,
                "sourcePath": candidate.relative_path,
            }
        )

    source_counts: dict[str, int] = {JACKETT_PROJECT: 0, PROWLARR_PROJECT: 0}
    for candidate in candidates:
        source_counts[candidate.project] += 1

    manifest = {
        "catalogVersion": 1,
        "definitionSchema": SCHEMA_VERSION,
        "generatedBy": GENERATED_BY,
        "definitionCount": len(entries),
        "sources": [
            {
                "project": JACKETT_PROJECT,
                "repository": JACKETT_REPOSITORY,
                "revision": jackett_revision,
                "discovered": jackett_count,
                "selected": source_counts[JACKETT_PROJECT],
                "license": SOURCE_LICENSE,
            },
            {
                "project": PROWLARR_PROJECT,
                "repository": PROWLARR_REPOSITORY,
                "revision": prowlarr_revision,
                "discovered": prowlarr_count,
                "selected": source_counts[PROWLARR_PROJECT],
                "license": SOURCE_LICENSE,
                "licenseBasis": "Cardigann definitions derived from Jackett GPL-2.0 sources",
            },
        ],
        "deduplication": deduplication,
        "definitions": entries,
    }
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()
    jackett_root = args.jackett_root.resolve()
    prowlarr_root = args.prowlarr_root.resolve()
    output = args.output.resolve()
    manifest = args.manifest.resolve()

    jackett = discover(
        project=JACKETT_PROJECT,
        repository=JACKETT_REPOSITORY,
        revision=args.jackett_revision,
        repository_root=jackett_root,
        definition_root=jackett_root / "src/Jackett.Common/Definitions",
        recursive=False,
    )
    prowlarr = discover(
        project=PROWLARR_PROJECT,
        repository=PROWLARR_REPOSITORY,
        revision=args.prowlarr_revision,
        repository_root=prowlarr_root,
        definition_root=prowlarr_root / "definitions",
        recursive=True,
    )
    selected, deduplication = select_candidates(jackett, prowlarr)
    write_catalog(
        selected,
        output,
        manifest,
        len(jackett),
        len(prowlarr),
        deduplication,
        args.jackett_revision,
        args.prowlarr_revision,
    )
    print(
        f"Imported {len(selected)} unique definitions "
        f"from {len(jackett)} Jackett and {len(prowlarr)} Prowlarr candidates."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
